import { useState, useEffect } from 'react';
import axios from 'axios';

export const fakeData ={
  "column-names": [
    "lmk-key",
    "address1",
    "address2",
    "address3",
    "postcode",
    "building-reference-number",
    "current-energy-rating",
    "potential-energy-rating",
    "current-energy-efficiency",
    "potential-energy-efficiency",
    "property-type",
    "built-form",
    "inspection-date",
    "local-authority",
    "constituency",
    "county",
    "lodgement-date",
    "transaction-type",
    "environment-impact-current",
    "environment-impact-potential",
    "energy-consumption-current",
    "energy-consumption-potential",
    "co2-emissions-current",
    "co2-emiss-curr-per-floor-area",
    "co2-emissions-potential",
    "lighting-cost-current",
    "lighting-cost-potential",
    "heating-cost-current",
    "heating-cost-potential",
    "hot-water-cost-current",
    "hot-water-cost-potential",
    "total-floor-area",
    "energy-tariff",
    "mains-gas-flag",
    "floor-level",
    "flat-top-storey",
    "flat-storey-count",
    "main-heating-controls",
    "multi-glaze-proportion",
    "glazed-type",
    "glazed-area",
    "extension-count",
    "number-habitable-rooms",
    "number-heated-rooms",
    "low-energy-lighting",
    "number-open-fireplaces",
    "hotwater-description",
    "hot-water-energy-eff",
    "hot-water-env-eff",
    "floor-description",
    "floor-energy-eff",
    "floor-env-eff",
    "windows-description",
    "windows-energy-eff",
    "windows-env-eff",
    "walls-description",
    "walls-energy-eff",
    "walls-env-eff",
    "secondheat-description",
    "sheating-energy-eff",
    "sheating-env-eff",
    "roof-description",
    "roof-energy-eff",
    "roof-env-eff",
    "mainheat-description",
    "mainheat-energy-eff",
    "mainheat-env-eff",
    "mainheatcont-description",
    "mainheatc-energy-eff",
    "mainheatc-env-eff",
    "lighting-description",
    "lighting-energy-eff",
    "lighting-env-eff",
    "main-fuel",
    "wind-turbine-count",
    "heat-loss-corridor",
    "unheated-corridor-length",
    "floor-height",
    "photo-supply",
    "solar-water-heating-flag",
    "mechanical-ventilation",
    "address",
    "local-authority-label",
    "constituency-label",
    "posttown",
    "construction-age-band",
    "lodgement-datetime",
    "tenure",
    "fixed-lighting-outlets-count",
    "low-energy-fixed-light-count",
    "uprn",
    "uprn-source"
  ],
  "rows": [
    {
      "low-energy-fixed-light-count": null,
      "address": "5 Steers Mead",
      "uprn-source": "Energy Assessor",
      "floor-height": "2.45",
      "heating-cost-potential": "360",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "64",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Average",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "86",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "894",
      "address3": null,
      "mainheatcont-description": "No thermostatic control of room temperature",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "8",
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "354",
      "county": null,
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.8",
      "number-heated-rooms": "4.0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "63",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2022-05-23",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "74.0",
      "address1": "5 Steers Mead",
      "heat-loss-corridor": null,
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "70.0",
      "building-reference-number": "10002900550",
      "environment-impact-current": "37",
      "co2-emissions-current": "5.1",
      "roof-description": "Pitched, no insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "4.0",
      "address2": null,
      "hot-water-env-eff": "Poor",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Poor",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0.0",
      "lighting-cost-potential": "60",
      "mainheat-env-eff": "Average",
      "multi-glaze-proportion": "100.0",
      "main-heating-controls": null,
      "lodgement-datetime": "2022-05-30 11:53:12",
      "flat-top-storey": null,
      "current-energy-rating": "F",
      "secondheat-description": "Room heaters, electric",
      "walls-env-eff": "Very Poor",
      "transaction-type": "ECO assessment",
      "uprn": "48066750",
      "current-energy-efficiency": "37",
      "energy-consumption-current": "424",
      "mainheat-description": "Room heaters, mains gas",
      "lighting-cost-current": "60",
      "lodgement-date": "2022-05-30",
      "extension-count": "1.0",
      "mainheatc-env-eff": "Poor",
      "lmk-key": "a77c1990d76645a050d63b3f3e72248a7e1a1f500c972c390c785ab8b4a7a094",
      "wind-turbine-count": "0",
      "tenure": "Rented (social)",
      "floor-level": null,
      "potential-energy-efficiency": "86",
      "hot-water-energy-eff": "Very Poor",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "Electric immersion, standard tariff"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "45 Steers Mead",
      "uprn-source": "Energy Assessor",
      "floor-height": "2.45",
      "heating-cost-potential": "328",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "60",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "85",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "535",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "8",
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "87",
      "county": null,
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.8",
      "number-heated-rooms": "4.0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "69",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2022-05-19",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "50.0",
      "address1": "45 Steers Mead",
      "heat-loss-corridor": null,
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "65.0",
      "building-reference-number": "10002818057",
      "environment-impact-current": "54",
      "co2-emissions-current": "3.2",
      "roof-description": "Pitched, 270 mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "4.0",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 88% of fixed outlets",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0.0",
      "lighting-cost-potential": "64",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100.0",
      "main-heating-controls": null,
      "lodgement-datetime": "2022-05-27 13:01:19",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "ECO assessment",
      "uprn": "48066790",
      "current-energy-efficiency": "60",
      "energy-consumption-current": "281",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "64",
      "lodgement-date": "2022-05-27",
      "extension-count": "0.0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "26ea505e23a4820b6b779590815ed917d1935ecb5863487016390c0e93ed00ec",
      "wind-turbine-count": "0",
      "tenure": "Rented (social)",
      "floor-level": null,
      "potential-energy-efficiency": "86",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "88",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "11 Steers Mead",
      "uprn-source": "Energy Assessor",
      "floor-height": "2.45",
      "heating-cost-potential": "289",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "58",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "89",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "375",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "9",
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "83",
      "county": null,
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.6",
      "number-heated-rooms": "5.0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "47",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2022-05-13",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "34.0",
      "address1": "11 Steers Mead",
      "heat-loss-corridor": null,
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "66.0",
      "building-reference-number": "10002571133",
      "environment-impact-current": "69",
      "co2-emissions-current": "2.2",
      "roof-description": "Pitched, 270 mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "5.0",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 89% of fixed outlets",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0.0",
      "lighting-cost-potential": "64",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100.0",
      "main-heating-controls": null,
      "lodgement-datetime": "2022-05-16 11:18:22",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "ECO assessment",
      "uprn": "48066756",
      "current-energy-efficiency": "70",
      "energy-consumption-current": "192",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "64",
      "lodgement-date": "2022-05-16",
      "extension-count": "0.0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "5f3bf8ef9948f9fc594b437d92fb73534c0739674de7ee52e44b1b53418cc192",
      "wind-turbine-count": "0",
      "tenure": "Rented (social)",
      "floor-level": null,
      "potential-energy-efficiency": "89",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "89",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "49 STEERS MEAD, MITCHAM",
      "uprn-source": "Energy Assessor",
      "floor-height": "2.4",
      "heating-cost-potential": "443",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "76",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "77",
      "glazed-type": "double glazing, unknown install date",
      "heating-cost-current": "550",
      "address3": null,
      "mainheatcont-description": "Programmer and room thermostat",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "6.0",
      "energy-tariff": "Unknown",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "119",
      "county": null,
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.4",
      "number-heated-rooms": "5.0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "118",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Mostly double glazing",
      "glazed-area": "Normal",
      "inspection-date": "2021-04-06",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "48.0",
      "address1": "49 STEERS MEAD",
      "heat-loss-corridor": null,
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "67.0",
      "building-reference-number": "10001116379",
      "environment-impact-current": "55",
      "co2-emissions-current": "3.2",
      "roof-description": "Pitched, no insulation (assumed)",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "5.0",
      "address2": "MITCHAM",
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Average",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0.0",
      "lighting-cost-potential": "56",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "90.0",
      "main-heating-controls": null,
      "lodgement-datetime": "2021-04-06 14:06:30",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "Room heaters, mains gas",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental",
      "uprn": "48066794",
      "current-energy-efficiency": "61",
      "energy-consumption-current": "273",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "56",
      "lodgement-date": "2021-04-06",
      "extension-count": "0.0",
      "mainheatc-env-eff": "Average",
      "lmk-key": "f876e5bcca5f892dd744e9e2241be5ac1bba59b42927e19363bbebb8900a7453",
      "wind-turbine-count": "0",
      "tenure": "Rented (private)",
      "floor-level": null,
      "potential-energy-efficiency": "81",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": "12.0",
      "address": "15 STEERS MEAD, MITCHAM",
      "uprn-source": "Energy Assessor",
      "floor-height": "2.42",
      "heating-cost-potential": "431",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "75",
      "construction-age-band": "England and Wales: 1900-1929",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "78",
      "glazed-type": "double glazing, unknown install date",
      "heating-cost-current": "494",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "12.0",
      "energy-tariff": "off-peak 10 hour",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "144",
      "county": null,
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.4",
      "number-heated-rooms": "3.0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "113",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Mostly double glazing",
      "glazed-area": "Normal",
      "inspection-date": "2020-11-26",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "46.0",
      "address1": "15 STEERS MEAD",
      "heat-loss-corridor": null,
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "67.0",
      "building-reference-number": "10000093992",
      "environment-impact-current": "58",
      "co2-emissions-current": "3.1",
      "roof-description": "Pitched, no insulation (assumed)",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "3.0",
      "address2": "MITCHAM",
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0.0",
      "lighting-cost-potential": "56",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "90.0",
      "main-heating-controls": null,
      "lodgement-datetime": "2020-11-26",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "marketed sale",
      "uprn": "48066760",
      "current-energy-efficiency": "63",
      "energy-consumption-current": "259",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "56",
      "lodgement-date": "2020-11-26",
      "extension-count": "0.0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "048d4149711d6e172fac12724a28b86d6dd6f06607cd23a771e5689a81f18f5f",
      "wind-turbine-count": "0.0",
      "tenure": "Owner-occupied",
      "floor-level": null,
      "potential-energy-efficiency": "82",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "43, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": "2.42",
      "heating-cost-potential": "366",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "50",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Good",
      "lighting-energy-eff": "Good",
      "environment-impact-potential": "86",
      "glazed-type": "double glazing installed during or after 2002",
      "heating-cost-current": "676",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "123",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.8",
      "number-heated-rooms": "5",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "66",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2016-10-14",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "58",
      "address1": "43, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "65",
      "building-reference-number": "3101379178",
      "environment-impact-current": "48",
      "co2-emissions-current": "3.7",
      "roof-description": "Pitched, 100 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "5",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Good",
      "windows-energy-eff": "Good",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 67% of fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "45",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2016-10-15 20:33:55",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (private)",
      "uprn": "48066788",
      "current-energy-efficiency": "55",
      "energy-consumption-current": "326",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "60",
      "lodgement-date": "2016-10-15",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "1090214679142016101520335518969148",
      "wind-turbine-count": "0",
      "tenure": "rental (private)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "87",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "67",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "53, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "293",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "77",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "90",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "408",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "132",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.5",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "41",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "36",
      "address1": "53, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "64",
      "building-reference-number": "6946521768",
      "environment-impact-current": "67",
      "co2-emissions-current": "2.3",
      "roof-description": "Pitched, 100 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "43",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-04-17 00:07:12",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066798",
      "current-energy-efficiency": "69",
      "energy-consumption-current": "206",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "43",
      "lodgement-date": "2015-04-17",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418269625712015041700071292950679",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "89",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "47, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "306",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "49",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "91",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "425",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "80",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "34",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "33",
      "address1": "47, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "64",
      "building-reference-number": "1646521768",
      "environment-impact-current": "69",
      "co2-emissions-current": "2.2",
      "roof-description": "Pitched, 100 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "43",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-04-16 23:23:55",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066792",
      "current-energy-efficiency": "71",
      "energy-consumption-current": "190",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "43",
      "lodgement-date": "2015-04-16",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "417935515652015041623235592950176",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "29, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "281",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "69",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "91",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "583",
      "address3": null,
      "mainheatcont-description": "Room thermostat only",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "182",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "32",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "55",
      "address1": "29, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Poor",
      "total-floor-area": "64",
      "building-reference-number": "9146521768",
      "environment-impact-current": "50",
      "co2-emissions-current": "3.5",
      "roof-description": "Pitched, 25 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Average",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Poor",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Poor",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "43",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2103",
      "lodgement-datetime": "2015-04-16 23:52:05",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066774",
      "current-energy-efficiency": "57",
      "energy-consumption-current": "309",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "43",
      "lodgement-date": "2015-04-16",
      "extension-count": "0",
      "mainheatc-env-eff": "Poor",
      "lmk-key": "418408345312015041623520592950971",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Average",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "7, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "345",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "67",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "87",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "531",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "101",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.7",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "53",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "37",
      "address1": "7, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "76",
      "building-reference-number": "0736521768",
      "environment-impact-current": "63",
      "co2-emissions-current": "2.8",
      "roof-description": "Pitched, 100 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "49",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-04-16 23:44:09",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066752",
      "current-energy-efficiency": "67",
      "energy-consumption-current": "212",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "49",
      "lodgement-date": "2015-04-16",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "417878159022015041623440971218605",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "88",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "31, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "475",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "78",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "77",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "706",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "132",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.5",
      "number-heated-rooms": "3",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "115",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "56",
      "address1": "31, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "70",
      "building-reference-number": "6246521768",
      "environment-impact-current": "49",
      "co2-emissions-current": "3.9",
      "roof-description": "Pitched, no insulation (assumed)",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "3",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "46",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-04-16 20:24:24",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066776",
      "current-energy-efficiency": "56",
      "energy-consumption-current": "315",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "46",
      "lodgement-date": "2015-04-16",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418225559922015041620242421698465",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "81",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "51, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "346",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "63",
      "construction-age-band": "England and Wales: 1900-1929",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Good",
      "environment-impact-potential": "87",
      "glazed-type": "double glazing, unknown install date",
      "heating-cost-current": "413",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "96",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.7",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "57",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-03-10",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "33",
      "address1": "51, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "67",
      "building-reference-number": "1066521768",
      "environment-impact-current": "69",
      "co2-emissions-current": "2.2",
      "roof-description": "Pitched, 270 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 67% of fixed outlets",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Poor",
      "photo-supply": null,
      "lighting-cost-potential": "44",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-03-15 23:22:31",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066796",
      "current-energy-efficiency": "70",
      "energy-consumption-current": "190",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "59",
      "lodgement-date": "2015-03-15",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "417898995912015031523223192950170",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "88",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "67",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "57, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "470",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "67",
      "construction-age-band": "England and Wales: before 1900",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Average",
      "environment-impact-potential": "79",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "637",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "101",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "100",
      "local-authority": "E09000024",
      "built-form": "Semi-Detached",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-03-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "46",
      "address1": "57, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "76",
      "building-reference-number": "3056521768",
      "environment-impact-current": "55",
      "co2-emissions-current": "3.5",
      "roof-description": "Pitched, 250 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Average",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 33% of fixed outlets",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Poor",
      "photo-supply": null,
      "lighting-cost-potential": "50",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-03-15 23:23:00",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066802",
      "current-energy-efficiency": "61",
      "energy-consumption-current": "260",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "83",
      "lodgement-date": "2015-03-15",
      "extension-count": "1",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418024459022015031523230001918335",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "82",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "33",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "17, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "475",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "63",
      "construction-age-band": "England and Wales: 1900-1929",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Good",
      "environment-impact-potential": "78",
      "glazed-type": "double glazing, unknown install date",
      "heating-cost-current": "535",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "96",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "113",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-03-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "43",
      "address1": "17, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "67",
      "building-reference-number": "7326521768",
      "environment-impact-current": "60",
      "co2-emissions-current": "2.9",
      "roof-description": "Pitched, no insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 56% of fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Poor",
      "photo-supply": null,
      "lighting-cost-potential": "44",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-03-15 23:22:10",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066762",
      "current-energy-efficiency": "64",
      "energy-consumption-current": "245",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "64",
      "lodgement-date": "2015-03-15",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418293659922015031523221031398975",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "81",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "56",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "37, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "435",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "70",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Poor",
      "environment-impact-potential": "82",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "631",
      "address3": null,
      "mainheatcont-description": "Programmer, no room thermostat",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Unknown",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "104",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.2",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "84",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-03-13",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "44",
      "address1": "37, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "80",
      "building-reference-number": "3768067568",
      "environment-impact-current": "56",
      "co2-emissions-current": "3.5",
      "roof-description": "Pitched, 150 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Very Poor",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Poor",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "No low energy lighting",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "52",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2102",
      "lodgement-datetime": "2015-03-13 16:17:01",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "marketed sale",
      "uprn": "48066782",
      "current-energy-efficiency": "62",
      "energy-consumption-current": "251",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "103",
      "lodgement-date": "2015-03-13",
      "extension-count": "1",
      "mainheatc-env-eff": "Very Poor",
      "lmk-key": "232207540452015031316170196950357",
      "wind-turbine-count": "0",
      "tenure": "owner-occupied",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "84",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "0",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "33, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "483",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "49",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "78",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "508",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "80",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "1.3",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "114",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-11",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "40",
      "address1": "33, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Poor",
      "total-floor-area": "64",
      "building-reference-number": "6826521768",
      "environment-impact-current": "63",
      "co2-emissions-current": "2.6",
      "roof-description": "Pitched, no insulation (assumed)",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Poor",
      "walls-energy-eff": "Good",
      "photo-supply": null,
      "lighting-cost-potential": "43",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-02-19 23:55:01",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Good",
      "transaction-type": "rental (social)",
      "uprn": "48066778",
      "current-energy-efficiency": "66",
      "energy-consumption-current": "227",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "43",
      "lodgement-date": "2015-02-19",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418261929842015021923550173159598",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "81",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, with internal insulation",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "19, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "300",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "69",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Average",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "90",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "827",
      "address3": null,
      "mainheatcont-description": "No thermostatic control of room temperature",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "118",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.5",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "40",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "67",
      "address1": "19, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "66",
      "building-reference-number": "4836521768",
      "environment-impact-current": "41",
      "co2-emissions-current": "4.4",
      "roof-description": "Pitched, 300 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Average",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Poor",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "44",
      "mainheat-env-eff": "Average",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2601",
      "lodgement-datetime": "2015-02-11 00:31:21",
      "flat-top-storey": null,
      "current-energy-rating": "E",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066764",
      "current-energy-efficiency": "47",
      "energy-consumption-current": "381",
      "mainheat-description": "Room heaters, mains gas",
      "lighting-cost-current": "44",
      "lodgement-date": "2015-02-11",
      "extension-count": "0",
      "mainheatc-env-eff": "Poor",
      "lmk-key": "418136629802015021100312177150818",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Average",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "27, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "292",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "70",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Average",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "90",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "603",
      "address3": null,
      "mainheatcont-description": "Automatic charge control",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "dual",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "224",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.5",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "36",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "76",
      "address1": "27, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "70",
      "building-reference-number": "5626521768",
      "environment-impact-current": "34",
      "co2-emissions-current": "5.3",
      "roof-description": "Pitched, 300 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Poor",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Average",
      "main-fuel": "electricity (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "46",
      "mainheat-env-eff": "Very Poor",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2402",
      "lodgement-datetime": "2015-02-11 00:27:20",
      "flat-top-storey": null,
      "current-energy-rating": "E",
      "secondheat-description": "Portable electric heaters (assumed)",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066772",
      "current-energy-efficiency": "54",
      "energy-consumption-current": "451",
      "mainheat-description": "Electric storage heaters",
      "lighting-cost-current": "51",
      "lodgement-date": "2015-02-11",
      "extension-count": "0",
      "mainheatc-env-eff": "Average",
      "lmk-key": "418186459022015021100272061918355",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Average",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "Electric immersion, off-peak"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "3, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "302",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "51",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "91",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "437",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "83",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "32",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "32",
      "address1": "3, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "70",
      "building-reference-number": "6536521768",
      "environment-impact-current": "69",
      "co2-emissions-current": "2.2",
      "roof-description": "Pitched, 300 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "46",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-02-11 00:06:41",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066748",
      "current-energy-efficiency": "71",
      "energy-consumption-current": "182",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "46",
      "lodgement-date": "2015-02-11",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418243659062015021100064151818765",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "3, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "302",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "51",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "91",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "437",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "83",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.4",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "32",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "32",
      "address1": "3, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "70",
      "building-reference-number": "6536521768",
      "environment-impact-current": "69",
      "co2-emissions-current": "2.2",
      "roof-description": "Pitched, 300 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "46",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-02-11 00:19:54",
      "flat-top-storey": null,
      "current-energy-rating": "C",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066748",
      "current-energy-efficiency": "71",
      "energy-consumption-current": "182",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "46",
      "lodgement-date": "2015-02-11",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418243695112015021100195492050675",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "1, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "325",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "67",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Good",
      "environment-impact-potential": "89",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "514",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "101",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "0.6",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "45",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2015-02-09",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "36",
      "address1": "1, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "76",
      "building-reference-number": "2026521768",
      "environment-impact-current": "64",
      "co2-emissions-current": "2.7",
      "roof-description": "Pitched, 300 mm loft insulation",
      "floor-energy-eff": "NO DATA!",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Very Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in all fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": null,
      "lighting-cost-potential": "49",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2015-02-10 23:54:17",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066745",
      "current-energy-efficiency": "68",
      "energy-consumption-current": "205",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "49",
      "lodgement-date": "2015-02-10",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "417959429042015021023541779150718",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "89",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "100",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": "4",
      "address": "9, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "344",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "59",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Poor",
      "environment-impact-potential": "92",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "630",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "18",
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "95",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": null,
      "constituency": "E14000823",
      "co2-emissions-potential": "0.5",
      "number-heated-rooms": "3",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "40",
      "local-authority": "E09000024",
      "built-form": "End-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2014-09-15",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "57",
      "address1": "9, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Very Good",
      "total-floor-area": "56",
      "building-reference-number": "7958687278",
      "environment-impact-current": "55",
      "co2-emissions-current": "3.2",
      "roof-description": "Pitched, 300+ mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "3",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Poor",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 22% of fixed outlets",
      "roof-env-eff": "Very Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0",
      "lighting-cost-potential": "37",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2014-09-15 21:45:42",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "None",
      "walls-env-eff": "Very Poor",
      "transaction-type": "marketed sale",
      "uprn": "48066754",
      "current-energy-efficiency": "57",
      "energy-consumption-current": "296",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "66",
      "lodgement-date": "2014-09-15",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "1205764271432014091521454258978609",
      "wind-turbine-count": "0",
      "tenure": "owner-occupied",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "90",
      "hot-water-energy-eff": "Good",
      "low-energy-lighting": "22",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": "9",
      "address": "59, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": null,
      "heating-cost-potential": "495",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "62",
      "construction-age-band": "England and Wales: before 1900",
      "potential-energy-rating": "B",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Good",
      "environment-impact-potential": "81",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "801",
      "address3": null,
      "mainheatcont-description": "Programmer and room thermostat",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": "14",
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "85",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": null,
      "constituency": "E14000823",
      "co2-emissions-potential": "1.6",
      "number-heated-rooms": "4",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "98",
      "local-authority": "E09000024",
      "built-form": "Semi-Detached",
      "number-open-fireplaces": "0",
      "windows-description": "Mostly double glazing",
      "glazed-area": "Normal",
      "inspection-date": "2013-10-31",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "54",
      "address1": "59, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "80",
      "building-reference-number": "1013485178",
      "environment-impact-current": "51",
      "co2-emissions-current": "4.4",
      "roof-description": "Pitched, 100 mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "4",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Average",
      "main-fuel": "mains gas (not community)",
      "lighting-env-eff": "Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 64% of fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0",
      "lighting-cost-potential": "47",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "89",
      "main-heating-controls": "2104",
      "lodgement-datetime": "2013-10-31 18:27:03",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "Room heaters, mains gas",
      "walls-env-eff": "Very Poor",
      "transaction-type": "marketed sale",
      "uprn": "48066804",
      "current-energy-efficiency": "55",
      "energy-consumption-current": "283",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "64",
      "lodgement-date": "2013-10-31",
      "extension-count": "1",
      "mainheatc-env-eff": "Average",
      "lmk-key": "1035033544452013103118270398779110",
      "wind-turbine-count": "0",
      "tenure": "owner-occupied",
      "floor-level": "NODATA!",
      "potential-energy-efficiency": "82",
      "hot-water-energy-eff": "Very Good",
      "low-energy-lighting": "64",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "49, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": "2.43",
      "heating-cost-potential": "491",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "114",
      "construction-age-band": "England and Wales: 1930-1949",
      "potential-energy-rating": "C",
      "mainheat-energy-eff": "Average",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Good",
      "environment-impact-potential": "64",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "649",
      "address3": null,
      "mainheatcont-description": "Programmer and room thermostat",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "161",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "3",
      "number-heated-rooms": "0",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "265",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "0",
      "windows-description": "Mostly double glazing",
      "glazed-area": "Normal",
      "inspection-date": "2011-04-06",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "64",
      "address1": "49, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Average",
      "total-floor-area": "67",
      "building-reference-number": "1715755868",
      "environment-impact-current": "50",
      "co2-emissions-current": "4.3",
      "roof-description": "Pitched, 75 mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "1",
      "address2": null,
      "hot-water-env-eff": "Good",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Average",
      "main-fuel": "mains gas - this is for backwards compatibility only and should not be used",
      "lighting-env-eff": "Good",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "Low energy lighting in 50% of fixed outlets",
      "roof-env-eff": "Average",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0",
      "lighting-cost-potential": "36",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "90",
      "main-heating-controls": "2104",
      "lodgement-datetime": "2011-04-06 17:27:10",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "Room heaters, mains gas",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (private)",
      "uprn": "48066794",
      "current-energy-efficiency": "57",
      "energy-consumption-current": "379",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "54",
      "lodgement-date": "2011-04-06",
      "extension-count": "0",
      "mainheatc-env-eff": "Average",
      "lmk-key": "614053017112011040617271095090187",
      "wind-turbine-count": "0",
      "tenure": "rental (private)",
      "floor-level": "NO DATA!",
      "potential-energy-efficiency": "70",
      "hot-water-energy-eff": "Average",
      "low-energy-lighting": "50",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system"
    },
    {
      "low-energy-fixed-light-count": null,
      "address": "3, Steers Mead",
      "uprn-source": "Address Matched",
      "floor-height": "2.45",
      "heating-cost-potential": "485",
      "unheated-corridor-length": null,
      "hot-water-cost-potential": "99",
      "construction-age-band": "England and Wales: 1900-1929",
      "potential-energy-rating": "D",
      "mainheat-energy-eff": "Good",
      "windows-env-eff": "Average",
      "lighting-energy-eff": "Very Poor",
      "environment-impact-potential": "58",
      "glazed-type": "double glazing installed before 2002",
      "heating-cost-current": "552",
      "address3": null,
      "mainheatcont-description": "Programmer, room thermostat and TRVs",
      "sheating-energy-eff": "N/A",
      "property-type": "House",
      "local-authority-label": "Merton",
      "fixed-lighting-outlets-count": null,
      "energy-tariff": "Single",
      "mechanical-ventilation": "natural",
      "hot-water-cost-current": "166",
      "county": "Greater London Authority",
      "postcode": "CR4 3JX",
      "solar-water-heating-flag": "N",
      "constituency": "E14000823",
      "co2-emissions-potential": "3.5",
      "number-heated-rooms": "5",
      "floor-description": "Suspended, no insulation (assumed)",
      "energy-consumption-potential": "285",
      "local-authority": "E09000024",
      "built-form": "Mid-Terrace",
      "number-open-fireplaces": "2",
      "windows-description": "Fully double glazed",
      "glazed-area": "Normal",
      "inspection-date": "2009-11-16",
      "mains-gas-flag": "Y",
      "co2-emiss-curr-per-floor-area": "67.3",
      "address1": "3, Steers Mead",
      "heat-loss-corridor": "NO DATA!",
      "flat-storey-count": null,
      "constituency-label": "Mitcham and Morden",
      "roof-energy-eff": "Good",
      "total-floor-area": "66",
      "building-reference-number": "6536521768",
      "environment-impact-current": "48",
      "co2-emissions-current": "4.4",
      "roof-description": "Pitched, 150mm loft insulation",
      "floor-energy-eff": "N/A",
      "number-habitable-rooms": "5",
      "address2": null,
      "hot-water-env-eff": "Average",
      "posttown": "MITCHAM",
      "mainheatc-energy-eff": "Good",
      "main-fuel": "mains gas - this is for backwards compatibility only and should not be used",
      "lighting-env-eff": "Very Poor",
      "windows-energy-eff": "Average",
      "floor-env-eff": "N/A",
      "sheating-env-eff": "N/A",
      "lighting-description": "No low energy lighting",
      "roof-env-eff": "Good",
      "walls-energy-eff": "Very Poor",
      "photo-supply": "0",
      "lighting-cost-potential": "33",
      "mainheat-env-eff": "Good",
      "multi-glaze-proportion": "100",
      "main-heating-controls": "2106",
      "lodgement-datetime": "2010-01-27 15:34:31",
      "flat-top-storey": null,
      "current-energy-rating": "D",
      "secondheat-description": "Room heaters, coal",
      "walls-env-eff": "Very Poor",
      "transaction-type": "rental (social)",
      "uprn": "48066748",
      "current-energy-efficiency": "56",
      "energy-consumption-current": "375",
      "mainheat-description": "Boiler and radiators, mains gas",
      "lighting-cost-current": "66",
      "lodgement-date": "2010-01-27",
      "extension-count": "0",
      "mainheatc-env-eff": "Good",
      "lmk-key": "418243695252010012715343102919675",
      "wind-turbine-count": "0",
      "tenure": "rental (social)",
      "floor-level": "NO DATA!",
      "potential-energy-efficiency": "66",
      "hot-water-energy-eff": "Average",
      "low-energy-lighting": "0",
      "walls-description": "Solid brick, as built, no insulation (assumed)",
      "hotwater-description": "From main system, no cylinder thermostat"
    }
  ]
}

export const useGetData = (url) => {
  // const [response, setResponse] = useState(null);
  // const [error, setError] = useState('');
  // const [loading, setloading] = useState(true);

  // async function fetchData() {
  //   await axios
  //     .get(url)
  //     .then((res) => {
  //       setResponse(res.data);
  //     })
  //     .catch((err) => {
  //       setError(err);
  //     })
  //     .finally(() => {
  //       setloading(false);
  //     });
  // }

  // useEffect(() => {
  //   fetchData();
  // }, [url]);

  // return { response, error, loading };
};


